CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER(3),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    TURNO VARCHAR2(50),
    ES_ADMIN NUMBER(1),
    CONSTRAINT ID_EM_EMP_PK PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT NOM_EMP_UQ UNIQUE (NOMBRE),
    CONSTRAINT APE_EMP_NN UNIQUE(APELLIDO),
    CONSTRAINT TUR_EMP_CHK CHECK (TURNO IN ('MAÑANA', 'TARDE', 'NOCHE')),
    CONSTRAINT ES_AD_EMP_CHK CHECK (ES_ADMIN IN (0,1))
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER(3),
    NOM_PROD VARCHAR2(50),
    DESCRIPCION VARCHAR2(100),
    TIPO VARCHAR2(50),
    PRECIO NUMBER(10,2) CONSTRAINT PRE_PRO_NN NOT NULL,
    STOCK NUMBER(10) CONSTRAINT STO_PRO_NN NOT NULL,
    CONSTRAINT ID_PROD_PROD_PK PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT NOM_PRO_UK UNIQUE (NOM_PROD),
    CONSTRAINT TIP_PRO_CHK CHECK (TIPO IN ('ANTICONCEPTIVO','ANALGESICO',
                                            'ANESTESICO','ANSIOLITICO',
                                            'ANTIBIOTICO','ANTICOLINERGICO',
                                            'ANTICONCEPTIVO','ANTICONVULSIVO',
                                            'ANTIDEPRESIVO','ANTIDIABETICO',
                                            'ANTIEMETICO','ANTIHELMINTICO',
                                            'ANTIHIPERTENSIVO','ANTIHISTAMINICO',
                                            'ANTINEOPLASICO','ANTIINFLAMATORIO',
                                            'ANTIPARKINSONIANO','ANTIMICOTICO',
                                            'ANTIPIRETICO','ANTIPSICOTICO',
                                            'ANTITUSIVO','ANTIDOTO',
                                            'BRONCODILATADOR','CARDIOTONICO',
                                            'CITOSTATICO','CITOTOXICO',
                                            'QUIMIOTERAPICO','HIPNOTICO',
                                            'HORMONOTERAPICO','QUIMIOTERAPICO',
                                            'RELAJANTE MUSCULAR'))
);

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR NUMBER(3) CONSTRAINT ID_PROV_PROV_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50) CONSTRAINT NOM_PRO_PROV_NN NOT NULL,
    CIF VARCHAR2(9) CONSTRAINT CIF_PRO_PROV_UK UNIQUE,
    TELEFONO VARCHAR2(12) CONSTRAINT TEL_PRO_PROV_NN NOT NULL
);

CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO NUMBER(3),
    ID_PROVEEDOR NUMBER(3),
    CONSTRAINT ID_PROD_ID_PROV_PRODPROV_PK PRIMARY KEY (ID_PRODUCTO, ID_PROVEEDOR),
    CONSTRAINT ID_PROD_PROV_PRO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT ID_PROV_PROV_PRO_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
);

CREATE TABLE VENTAS (
    ID_VENTA NUMBER(5) CONSTRAINT ID_VEN_VEN_PK PRIMARY KEY,
    ID_EMPLEADO NUMBER(3),
    HORA_VENTA VARCHAR2(8) CONSTRAINT HOR_VENT_NN NOT NULL,
    FECHA_VENTA DATE DEFAULT SYSDATE,
    CONSTRAINT ID_EMP_VENT_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
);

CREATE TABLE VENTA_PRODUCTO (
    ID_VENTA NUMBER(3),
    ID_PRODUCTO NUMBER(3),
    CANTIDAD_VENTA NUMBER(2) CONSTRAINT CANT_VENT_NN NOT NULL,
    CONSTRAINT ID_EMP_ID_PROD_VENT_PK PRIMARY KEY (ID_VENTA, ID_PRODUCTO),
    CONSTRAINT ID_EMP_VENT_FK FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID_VENTA),
    CONSTRAINT ID_PROD_VENT_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE SOLICITUD_STOCK (
    ID_EMPLEADO NUMBER(3),
    ID_PRODUCTO NUMBER(3),
    FECHA_PEDIDO DATE DEFAULT SYSDATE,
    HORA_PEDIDO VARCHAR2(8) CONSTRAINT HOR_PED_SOL_NN NOT NULL,
    CANTIDAD_PEDIDO NUMBER(2) CONSTRAINT CANT_PEDI_SOL_NN NOT NULL,
    CONSTRAINT ID_EMP_ID_PROD_SOL_PK PRIMARY KEY (ID_EMPLEADO, ID_PRODUCTO),
    CONSTRAINT ID_EMP_SOL_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    CONSTRAINT ID_PROD_SOL_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE STOCK_PRODUCTO (
    ID_PRODUCTO NUMBER(3),
    STOCK NUMBER(10) CONSTRAINT STO_PRO_STO_NN NOT NULL,
    CONSTRAINT ID_PROD_STO_STO_PROD_PK PRIMARY KEY (ID_PRODUCTO, STOCK),
    CONSTRAINT ID_PROD_STO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT STO_PRO_STO_FK FOREIGN KEY (STOCK) REFERENCES PRODUCTO (STOCK)
);









