CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER(3),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    TURNO VARCHAR2(50),
    ES_ADMIN NUMBER(1)
    CONSTRAINT ID_EM_EMP_PK PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT NOM_EMP_UK UNIQUE (NOMBRE, APELLIDO),
    CONSTRAINT TUR_EMP_NN NOT NULL (TURNO),
    CONSTRAINT ES_AD_EMP_CHK CHECK (ES_ADMIN IN (0,1))
);

CREATE SEQUENCE EMPLEADO_SEQ
START WITH 4
    INCREMENT BY 1
    MAXVALUE 999
    MINVALUE 1
    CACHE 4
    ORDER;

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER(3),
    NOM_PROD VARCHAR2(50),
    DESCRIPCION VARCHAR2(100),
    TIPO VARCHAR2(50),
    PRECIO NUMBER(10,2),
    STOCK NUMBER(10),
    CONSTRAINT ID_PROD_PROD_PK PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT NOM_PRO_UK UNIQUE (NOM_PROD),
    CONSTRAINT TIP_PRO_CHK CHECK (TIPO IN ('ANTICONCEPTIVO','ANALGESICO','ANESTESICO','ANSIOLITICO','ANTIBIOTICO','ANTICOLINERGICO','ANTICONCEPTIVO','ANTICONVULSIVO','ANTIDEPRESIVO','ANTIDIABETICO','ANTIEMETICO','ANTIHELMINTICO','ANTIHIPERTENSIVO','ANTIHISTAMINICO','ANTINEOPLASICO','ANTIINFLAMATORIO','ANTIPARKINSONIANO','ANTIMICOTICO','ANTIPIRETICO','ANTIPSICOTICO','ANTITUSIVO','ANTIDOTO','BRONCODILATADOR','CARDIOTONICO','CITOSTATICO','CITOTOXICO','QUIMIOTERAPICO','HIPNOTICO','HORMONOTERAPICO','QUIMIOTERAPICO','RELAJANTE MUSCULAR')),
    CONSTRAINT STO_PRO_NN NOT NULL (STOCK),
    CONSTRAINT PRE_PRO_NN NOT NULL (PRECIO)
);

CREATE SEQUENCE PRODUCTO_SEQ
START WITH 4
    INCREMENT BY 1
    MAXVALUE 999
    MINVALUE 1
    CACHE 4
    ORDER;

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR NUMBER(3),
    NOMBRE VARCHAR2(50),
    CIF VARCHAR2(9),
    TELEFONO VARCHAR2(12),
    CONSTRAINT ID_PROV_PROV_PK PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT NOM_PRO_PROV_UK UNIQUE (NOMBRE),
    CONSTRAINT CIF_PRO_PROV_UK UNIQUE (CIF),
    CONSTRAINT TEL_PRO_PROV_UK UNIQUE (TELEFONO)
);

CREATE SEQUENCE PROVEEDOR_SEQ
START WITH 4
    INCREMENT BY 1
    MAXVALUE 999
    MINVALUE 1
    CACHE 4
    ORDER;

CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO NUMBER(3),
    ID_PROVEEDOR NUMBER(3),
    CONSTRAINT ID_PROD_ID_PROV_PRODPROV_PK PRIMARY KEY (ID_PRODUCTO, ID_PROVEEDOR),
    CONSTRAINT ID_PROD_PROV_PRO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT ID_PROV_PROV_PRO_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
);

CREATE TABLE VENTAS (
    ID_EMPLEADO NUMBER(3),
    ID_PRODUCTO NUMBER(3),
    CANTIDAD_VENTA NUMBER(2),
    HORA_VENTA VARCHAR2(8),
    FECHA_VENTA DATE DEFAULT SYSDATE,
    CONSTRAINT ID_EMP_ID_PROD_VENT_PK PRIMARY KEY (ID_EMPLEADO, ID_PRODUCTO),
    CONSTRAINT ID_EMP_VENT_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    CONSTRAINT ID_PROD_VENT_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
    CONSTRAINT CANT_VENT_NN NOT NULL (CANTIDAD_VENTA),
    CONSTRAINT HOR_VENT_NN NOT NULL (HORA_VENTA)
);

CREATE TABLE SOLICITUD_STOCK (
    ID_EMPLEADO NUMBER(3),
    ID_PRODUCTO NUMBER(3),
    CONSTRAINT ID_EMP_ID_PROD_SOL_PK PRIMARY KEY (ID_EMPLEADO, ID_PRODUCTO),
    CONSTRAINT ID_EMP_SOL_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    CONSTRAINT ID_PROD_SOL_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
    FECHA_PEDIDO DATE DEFAULT SYSDATE,
    HORA_PEDIDO VARCHAR2(8),
    CANTIDAD_PEDIDO NUMBER(2),
);