CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER(3),
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    TURNO VARCHAR2(50),
    VENTA_MES NUMBER(10,2),
    ES_ADMIN NUMBER(1)
    CONSTRAINT ID_EM_EMP_PK PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT NOM_EMP_UK UNIQUE (NOMBRE, APELLIDO),
    CONSTRAINT TUR_EMP_NN NOT NULL (TURNO),
    CONSTRAINT ES_AD_EMP_CHK CHECK (ES_ADMIN IN (0,1))
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER(3),
    NOM_PROD VARCHAR2(50),
    DESCRIPCION VARCHAR2(100),
    TIPO VARCHAR2(50),
    PRECIO NUMBER(10,2),
    STOCK NUMBER(10),
    CONSTRAINT ID_PROD_PROD_PK PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT NOM_PRO_UK UNIQUE (NOM_PROD),
    CONSTRAINT TIP_PRO_CHK CHECK (TIPO IN ('ANTICONCEPTIVO',''))
    CONSTRAINT STO_PRO_NN NOT NULL (STOCK),
    CONSTRAINT PRE_PRO_NN NOT NULL (PRECIO)
);

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR NUMBER(3),
    NOMBRE VARCHAR2(50),
    CIF VARCHAR2(9),
    TELEFONO VARCHAR2(12),
    CONSTRAINT ID_PROV_PROV_PK PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT NOM_PRO_PROV_UK UNIQUE (NOMBRE),
    CONSTRAINT CIF_PRO_PROV_UK UNIQUE (CIF),
    CONSTRAINT TEL_PRO_PROV_UK UNIQUE (TELEFONO)
);

CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO NUMBER(3),
    ID_PROVEEDOR NUMBER(3),
    CONSTRAINT ID_PROD_PROV_PRO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT ID_PROV_PROV_PRO_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
);

CREATE TABLE EMPLEADO_PRODUCTO (
    ID_EMPLEADO NUMBER(3),
    ID_PRODUCTO NUMBER(3),
    CANTIDAD_VENTA NUMBER(2),
    HORA_VENTA VARCHAR2(8),
    FECHA_VENTA DATE,
    CONSTRAINT ID_EMP_PROD_EMP_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    CONSTRAINT ID_PROD_EMP_EMP_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
    CONSTRAINT CANT_EMP_EMP_NN NOT NULL (CANTIDAD_VENTA),
    CONSTRAINT HOR_EMP_EMP_NN NOT NULL (HORA_VENTA),
    CONSTRAINT FEC_EMP_EMP_DF SYSDATE (FECHA_VENTA)
);